### ISSUE TITLE
Only images are highlighted as changed when adding entire new chapter

### ISSUE THREAD

**Issue by joelostblom** [trevorcampbell/website_diff#23]
In this PR I added an entire new chapter to the built book https://github.com/joelostblom/viz-oer/pull/29. However, [in the deploy preview](https://joelostblom.github.io/viz-oer/diff29/chapter_1.html), only the images are highlighted in green as "changed", not the text. I was expecting the text to also be green, but maybe there is some max on how big of a change is marked up?

I'll leave that PR up until you have had time to have a look

**Comment by trevorcampbell** [comment]
Interesting. I think what's happening is:
- the images are diffed separately (and independently) from `.html` pages, so the code is correctly finding new graphics and highlighting them
- Our convention for new `.html` pages is to just colour links pointing to them green, but otherwise leave them alone

But seeing your example, it is a little bit weird. It's hard to reliably apply a style over a whole page (which has its own nested element tree each with their own style overrides). I wonder if just inserting a large top element with green text "This whole page is new" or something like that is the right strategy...

**Comment by joelostblom** [comment]
I see, the current convention of not marking up entire pages makes sense, and I think it would be helpful with a banner/message on the top of a file if the entire file is new, as you suggested.
